[APP]
ScriptPath    = D:/GBT/apk_server/index.js | APK Server
ScriptPath    = D:/GBT/srtec_pms_report/dist/backend/server.js | Report Server
; OPTIONAL
NodePath      = 
; true / false
EnableLogging = true
; OPTIONAL
LogFile       = logs/app.log
; Auto start with Windows
AutoStart     = true
; Optional delay before starting servers on launch (in seconds)
Delay         = 30
