[APP]
; REQUIRED
ScriptPath    = D:/GBT/apk_server/index.js
; OPTIONAL
NodePath      = 
; true / false
EnableLogging = true
; OPTIONAL
LogFile       = logs/app.log
; Auto start with Windows
AutoStart     = false
